import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Quisco con Next.js App Router y prisma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-zinc-900">
        {children}
      </body>
    </html>
  );
}
